/* This file was generated by SableCC (http://www.sablecc.org/). */

package especificacao.node;

import especificacao.analysis.*;

@SuppressWarnings("nls")
public final class ADivTermoAritmetico extends PTermoAritmetico
{
    private PTermoAritmetico _termoAritmetico_;
    private TDiv _div_;
    private PFatorAritmetico _fatorAritmetico_;

    public ADivTermoAritmetico()
    {
        // Constructor
    }

    public ADivTermoAritmetico(
        @SuppressWarnings("hiding") PTermoAritmetico _termoAritmetico_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PFatorAritmetico _fatorAritmetico_)
    {
        // Constructor
        setTermoAritmetico(_termoAritmetico_);

        setDiv(_div_);

        setFatorAritmetico(_fatorAritmetico_);

    }

    @Override
    public Object clone()
    {
        return new ADivTermoAritmetico(
            cloneNode(this._termoAritmetico_),
            cloneNode(this._div_),
            cloneNode(this._fatorAritmetico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivTermoAritmetico(this);
    }

    public PTermoAritmetico getTermoAritmetico()
    {
        return this._termoAritmetico_;
    }

    public void setTermoAritmetico(PTermoAritmetico node)
    {
        if(this._termoAritmetico_ != null)
        {
            this._termoAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetico_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PFatorAritmetico getFatorAritmetico()
    {
        return this._fatorAritmetico_;
    }

    public void setFatorAritmetico(PFatorAritmetico node)
    {
        if(this._fatorAritmetico_ != null)
        {
            this._fatorAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorAritmetico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoAritmetico_)
            + toString(this._div_)
            + toString(this._fatorAritmetico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoAritmetico_ == child)
        {
            this._termoAritmetico_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._fatorAritmetico_ == child)
        {
            this._fatorAritmetico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoAritmetico_ == oldChild)
        {
            setTermoAritmetico((PTermoAritmetico) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._fatorAritmetico_ == oldChild)
        {
            setFatorAritmetico((PFatorAritmetico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
