/* This file was generated by SableCC (http://www.sablecc.org/). */

package especificacao.node;

import especificacao.analysis.*;

@SuppressWarnings("nls")
public final class AMultTermoAritmetico extends PTermoAritmetico
{
    private PTermoAritmetico _termoAritmetico_;
    private TMult _mult_;
    private PFatorAritmetico _fatorAritmetico_;

    public AMultTermoAritmetico()
    {
        // Constructor
    }

    public AMultTermoAritmetico(
        @SuppressWarnings("hiding") PTermoAritmetico _termoAritmetico_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PFatorAritmetico _fatorAritmetico_)
    {
        // Constructor
        setTermoAritmetico(_termoAritmetico_);

        setMult(_mult_);

        setFatorAritmetico(_fatorAritmetico_);

    }

    @Override
    public Object clone()
    {
        return new AMultTermoAritmetico(
            cloneNode(this._termoAritmetico_),
            cloneNode(this._mult_),
            cloneNode(this._fatorAritmetico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultTermoAritmetico(this);
    }

    public PTermoAritmetico getTermoAritmetico()
    {
        return this._termoAritmetico_;
    }

    public void setTermoAritmetico(PTermoAritmetico node)
    {
        if(this._termoAritmetico_ != null)
        {
            this._termoAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetico_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PFatorAritmetico getFatorAritmetico()
    {
        return this._fatorAritmetico_;
    }

    public void setFatorAritmetico(PFatorAritmetico node)
    {
        if(this._fatorAritmetico_ != null)
        {
            this._fatorAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorAritmetico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoAritmetico_)
            + toString(this._mult_)
            + toString(this._fatorAritmetico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoAritmetico_ == child)
        {
            this._termoAritmetico_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._fatorAritmetico_ == child)
        {
            this._fatorAritmetico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoAritmetico_ == oldChild)
        {
            setTermoAritmetico((PTermoAritmetico) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._fatorAritmetico_ == oldChild)
        {
            setFatorAritmetico((PFatorAritmetico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
