/* This file was generated by SableCC (http://www.sablecc.org/). */

package especificacao.node;

import especificacao.analysis.*;

@SuppressWarnings("nls")
public final class AParaPassoComandos extends PComandos
{
    private PVar _var_;
    private TNInteiro _inicio_;
    private TNInteiro _passos_;
    private TNInteiro _fim_;

    public AParaPassoComandos()
    {
        // Constructor
    }

    public AParaPassoComandos(
        @SuppressWarnings("hiding") PVar _var_,
        @SuppressWarnings("hiding") TNInteiro _inicio_,
        @SuppressWarnings("hiding") TNInteiro _passos_,
        @SuppressWarnings("hiding") TNInteiro _fim_)
    {
        // Constructor
        setVar(_var_);

        setInicio(_inicio_);

        setPassos(_passos_);

        setFim(_fim_);

    }

    @Override
    public Object clone()
    {
        return new AParaPassoComandos(
            cloneNode(this._var_),
            cloneNode(this._inicio_),
            cloneNode(this._passos_),
            cloneNode(this._fim_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaPassoComandos(this);
    }

    public PVar getVar()
    {
        return this._var_;
    }

    public void setVar(PVar node)
    {
        if(this._var_ != null)
        {
            this._var_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._var_ = node;
    }

    public TNInteiro getInicio()
    {
        return this._inicio_;
    }

    public void setInicio(TNInteiro node)
    {
        if(this._inicio_ != null)
        {
            this._inicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicio_ = node;
    }

    public TNInteiro getPassos()
    {
        return this._passos_;
    }

    public void setPassos(TNInteiro node)
    {
        if(this._passos_ != null)
        {
            this._passos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passos_ = node;
    }

    public TNInteiro getFim()
    {
        return this._fim_;
    }

    public void setFim(TNInteiro node)
    {
        if(this._fim_ != null)
        {
            this._fim_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fim_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._var_)
            + toString(this._inicio_)
            + toString(this._passos_)
            + toString(this._fim_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._var_ == child)
        {
            this._var_ = null;
            return;
        }

        if(this._inicio_ == child)
        {
            this._inicio_ = null;
            return;
        }

        if(this._passos_ == child)
        {
            this._passos_ = null;
            return;
        }

        if(this._fim_ == child)
        {
            this._fim_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._var_ == oldChild)
        {
            setVar((PVar) newChild);
            return;
        }

        if(this._inicio_ == oldChild)
        {
            setInicio((TNInteiro) newChild);
            return;
        }

        if(this._passos_ == oldChild)
        {
            setPassos((TNInteiro) newChild);
            return;
        }

        if(this._fim_ == oldChild)
        {
            setFim((TNInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
