/* This file was generated by SableCC (http://www.sablecc.org/). */

package especificacao.node;

import especificacao.analysis.*;

@SuppressWarnings("nls")
public final class TAspasDupla extends Token
{
    public TAspasDupla()
    {
        super.setText("\"");
    }

    public TAspasDupla(int line, int pos)
    {
        super.setText("\"");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAspasDupla(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAspasDupla(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAspasDupla text.");
    }
}
