/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ADivTermoAritmetrico extends PTermoAritmetrico
{
    private PTermoAritmetrico _termoAritmetrico_;
    private TDiv _div_;
    private PFatorAritmetrico _fatorAritmetrico_;

    public ADivTermoAritmetrico()
    {
        // Constructor
    }

    public ADivTermoAritmetrico(
        @SuppressWarnings("hiding") PTermoAritmetrico _termoAritmetrico_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PFatorAritmetrico _fatorAritmetrico_)
    {
        // Constructor
        setTermoAritmetrico(_termoAritmetrico_);

        setDiv(_div_);

        setFatorAritmetrico(_fatorAritmetrico_);

    }

    @Override
    public Object clone()
    {
        return new ADivTermoAritmetrico(
            cloneNode(this._termoAritmetrico_),
            cloneNode(this._div_),
            cloneNode(this._fatorAritmetrico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivTermoAritmetrico(this);
    }

    public PTermoAritmetrico getTermoAritmetrico()
    {
        return this._termoAritmetrico_;
    }

    public void setTermoAritmetrico(PTermoAritmetrico node)
    {
        if(this._termoAritmetrico_ != null)
        {
            this._termoAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetrico_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PFatorAritmetrico getFatorAritmetrico()
    {
        return this._fatorAritmetrico_;
    }

    public void setFatorAritmetrico(PFatorAritmetrico node)
    {
        if(this._fatorAritmetrico_ != null)
        {
            this._fatorAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorAritmetrico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoAritmetrico_)
            + toString(this._div_)
            + toString(this._fatorAritmetrico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoAritmetrico_ == child)
        {
            this._termoAritmetrico_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._fatorAritmetrico_ == child)
        {
            this._fatorAritmetrico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoAritmetrico_ == oldChild)
        {
            setTermoAritmetrico((PTermoAritmetrico) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._fatorAritmetrico_ == oldChild)
        {
            setFatorAritmetrico((PFatorAritmetrico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
