/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AExpParentesesFatorAritmetrico extends PFatorAritmetrico
{
    private TEsqParentese _esqParentese_;
    private PExpAritmetrica _expAritmetrica_;
    private TDirParentese _dirParentese_;

    public AExpParentesesFatorAritmetrico()
    {
        // Constructor
    }

    public AExpParentesesFatorAritmetrico(
        @SuppressWarnings("hiding") TEsqParentese _esqParentese_,
        @SuppressWarnings("hiding") PExpAritmetrica _expAritmetrica_,
        @SuppressWarnings("hiding") TDirParentese _dirParentese_)
    {
        // Constructor
        setEsqParentese(_esqParentese_);

        setExpAritmetrica(_expAritmetrica_);

        setDirParentese(_dirParentese_);

    }

    @Override
    public Object clone()
    {
        return new AExpParentesesFatorAritmetrico(
            cloneNode(this._esqParentese_),
            cloneNode(this._expAritmetrica_),
            cloneNode(this._dirParentese_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpParentesesFatorAritmetrico(this);
    }

    public TEsqParentese getEsqParentese()
    {
        return this._esqParentese_;
    }

    public void setEsqParentese(TEsqParentese node)
    {
        if(this._esqParentese_ != null)
        {
            this._esqParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqParentese_ = node;
    }

    public PExpAritmetrica getExpAritmetrica()
    {
        return this._expAritmetrica_;
    }

    public void setExpAritmetrica(PExpAritmetrica node)
    {
        if(this._expAritmetrica_ != null)
        {
            this._expAritmetrica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAritmetrica_ = node;
    }

    public TDirParentese getDirParentese()
    {
        return this._dirParentese_;
    }

    public void setDirParentese(TDirParentese node)
    {
        if(this._dirParentese_ != null)
        {
            this._dirParentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dirParentese_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esqParentese_)
            + toString(this._expAritmetrica_)
            + toString(this._dirParentese_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esqParentese_ == child)
        {
            this._esqParentese_ = null;
            return;
        }

        if(this._expAritmetrica_ == child)
        {
            this._expAritmetrica_ = null;
            return;
        }

        if(this._dirParentese_ == child)
        {
            this._dirParentese_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esqParentese_ == oldChild)
        {
            setEsqParentese((TEsqParentese) newChild);
            return;
        }

        if(this._expAritmetrica_ == oldChild)
        {
            setExpAritmetrica((PExpAritmetrica) newChild);
            return;
        }

        if(this._dirParentese_ == oldChild)
        {
            setDirParentese((TDirParentese) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
