/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AFatorTermoAritmetrico extends PTermoAritmetrico
{
    private PFatorAritmetrico _fatorAritmetrico_;

    public AFatorTermoAritmetrico()
    {
        // Constructor
    }

    public AFatorTermoAritmetrico(
        @SuppressWarnings("hiding") PFatorAritmetrico _fatorAritmetrico_)
    {
        // Constructor
        setFatorAritmetrico(_fatorAritmetrico_);

    }

    @Override
    public Object clone()
    {
        return new AFatorTermoAritmetrico(
            cloneNode(this._fatorAritmetrico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorTermoAritmetrico(this);
    }

    public PFatorAritmetrico getFatorAritmetrico()
    {
        return this._fatorAritmetrico_;
    }

    public void setFatorAritmetrico(PFatorAritmetrico node)
    {
        if(this._fatorAritmetrico_ != null)
        {
            this._fatorAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorAritmetrico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fatorAritmetrico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fatorAritmetrico_ == child)
        {
            this._fatorAritmetrico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fatorAritmetrico_ == oldChild)
        {
            setFatorAritmetrico((PFatorAritmetrico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
