/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AMenosExpAritmetrica extends PExpAritmetrica
{
    private PExpAritmetrica _expAritmetrica_;
    private TMenos _menos_;
    private PTermoAritmetrico _termoAritmetrico_;

    public AMenosExpAritmetrica()
    {
        // Constructor
    }

    public AMenosExpAritmetrica(
        @SuppressWarnings("hiding") PExpAritmetrica _expAritmetrica_,
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PTermoAritmetrico _termoAritmetrico_)
    {
        // Constructor
        setExpAritmetrica(_expAritmetrica_);

        setMenos(_menos_);

        setTermoAritmetrico(_termoAritmetrico_);

    }

    @Override
    public Object clone()
    {
        return new AMenosExpAritmetrica(
            cloneNode(this._expAritmetrica_),
            cloneNode(this._menos_),
            cloneNode(this._termoAritmetrico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosExpAritmetrica(this);
    }

    public PExpAritmetrica getExpAritmetrica()
    {
        return this._expAritmetrica_;
    }

    public void setExpAritmetrica(PExpAritmetrica node)
    {
        if(this._expAritmetrica_ != null)
        {
            this._expAritmetrica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAritmetrica_ = node;
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PTermoAritmetrico getTermoAritmetrico()
    {
        return this._termoAritmetrico_;
    }

    public void setTermoAritmetrico(PTermoAritmetrico node)
    {
        if(this._termoAritmetrico_ != null)
        {
            this._termoAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetrico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAritmetrica_)
            + toString(this._menos_)
            + toString(this._termoAritmetrico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAritmetrica_ == child)
        {
            this._expAritmetrica_ = null;
            return;
        }

        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._termoAritmetrico_ == child)
        {
            this._termoAritmetrico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAritmetrica_ == oldChild)
        {
            setExpAritmetrica((PExpAritmetrica) newChild);
            return;
        }

        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._termoAritmetrico_ == oldChild)
        {
            setTermoAritmetrico((PTermoAritmetrico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
