/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AMenorIgualExpRelacional extends PExpRelacional
{
    private PExpAritmetica _expAritmetica_;
    private TMenorIgual _menorIgual_;
    private PTermoAritmetico _termoAritmetico_;

    public AMenorIgualExpRelacional()
    {
        // Constructor
    }

    public AMenorIgualExpRelacional(
        @SuppressWarnings("hiding") PExpAritmetica _expAritmetica_,
        @SuppressWarnings("hiding") TMenorIgual _menorIgual_,
        @SuppressWarnings("hiding") PTermoAritmetico _termoAritmetico_)
    {
        // Constructor
        setExpAritmetica(_expAritmetica_);

        setMenorIgual(_menorIgual_);

        setTermoAritmetico(_termoAritmetico_);

    }

    @Override
    public Object clone()
    {
        return new AMenorIgualExpRelacional(
            cloneNode(this._expAritmetica_),
            cloneNode(this._menorIgual_),
            cloneNode(this._termoAritmetico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorIgualExpRelacional(this);
    }

    public PExpAritmetica getExpAritmetica()
    {
        return this._expAritmetica_;
    }

    public void setExpAritmetica(PExpAritmetica node)
    {
        if(this._expAritmetica_ != null)
        {
            this._expAritmetica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expAritmetica_ = node;
    }

    public TMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(TMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    public PTermoAritmetico getTermoAritmetico()
    {
        return this._termoAritmetico_;
    }

    public void setTermoAritmetico(PTermoAritmetico node)
    {
        if(this._termoAritmetico_ != null)
        {
            this._termoAritmetico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expAritmetica_)
            + toString(this._menorIgual_)
            + toString(this._termoAritmetico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expAritmetica_ == child)
        {
            this._expAritmetica_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        if(this._termoAritmetico_ == child)
        {
            this._termoAritmetico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expAritmetica_ == oldChild)
        {
            setExpAritmetica((PExpAritmetica) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((TMenorIgual) newChild);
            return;
        }

        if(this._termoAritmetico_ == oldChild)
        {
            setTermoAritmetico((PTermoAritmetico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
