/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class AMenosFatorAritmetrico extends PFatorAritmetrico
{
    private TMenos _menos_;
    private PFatorAritmetrico _fatorAritmetrico_;

    public AMenosFatorAritmetrico()
    {
        // Constructor
    }

    public AMenosFatorAritmetrico(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PFatorAritmetrico _fatorAritmetrico_)
    {
        // Constructor
        setMenos(_menos_);

        setFatorAritmetrico(_fatorAritmetrico_);

    }

    @Override
    public Object clone()
    {
        return new AMenosFatorAritmetrico(
            cloneNode(this._menos_),
            cloneNode(this._fatorAritmetrico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosFatorAritmetrico(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PFatorAritmetrico getFatorAritmetrico()
    {
        return this._fatorAritmetrico_;
    }

    public void setFatorAritmetrico(PFatorAritmetrico node)
    {
        if(this._fatorAritmetrico_ != null)
        {
            this._fatorAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorAritmetrico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._fatorAritmetrico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._fatorAritmetrico_ == child)
        {
            this._fatorAritmetrico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._fatorAritmetrico_ == oldChild)
        {
            setFatorAritmetrico((PFatorAritmetrico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
