/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesVarVarList extends PVarList
{
    private PVarV _varV_;

    public ASimplesVarVarList()
    {
        // Constructor
    }

    public ASimplesVarVarList(
        @SuppressWarnings("hiding") PVarV _varV_)
    {
        // Constructor
        setVarV(_varV_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesVarVarList(
            cloneNode(this._varV_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesVarVarList(this);
    }

    public PVarV getVarV()
    {
        return this._varV_;
    }

    public void setVarV(PVarV node)
    {
        if(this._varV_ != null)
        {
            this._varV_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varV_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varV_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varV_ == child)
        {
            this._varV_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varV_ == oldChild)
        {
            setVarV((PVarV) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
