/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ASimplesDeclaracao extends PDeclaracao
{
    private PDeclaracaoSimple _declaracaoSimple_;

    public ASimplesDeclaracao()
    {
        // Constructor
    }

    public ASimplesDeclaracao(
        @SuppressWarnings("hiding") PDeclaracaoSimple _declaracaoSimple_)
    {
        // Constructor
        setDeclaracaoSimple(_declaracaoSimple_);

    }

    @Override
    public Object clone()
    {
        return new ASimplesDeclaracao(
            cloneNode(this._declaracaoSimple_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplesDeclaracao(this);
    }

    public PDeclaracaoSimple getDeclaracaoSimple()
    {
        return this._declaracaoSimple_;
    }

    public void setDeclaracaoSimple(PDeclaracaoSimple node)
    {
        if(this._declaracaoSimple_ != null)
        {
            this._declaracaoSimple_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoSimple_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoSimple_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoSimple_ == child)
        {
            this._declaracaoSimple_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoSimple_ == oldChild)
        {
            setDeclaracaoSimple((PDeclaracaoSimple) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
