/* This file was generated by SableCC (http://www.sablecc.org/). */

package simpleAdder.node;

import simpleAdder.analysis.*;

@SuppressWarnings("nls")
public final class ATermoExpAritmetrica extends PExpAritmetrica
{
    private PTermoAritmetrico _termoAritmetrico_;

    public ATermoExpAritmetrica()
    {
        // Constructor
    }

    public ATermoExpAritmetrica(
        @SuppressWarnings("hiding") PTermoAritmetrico _termoAritmetrico_)
    {
        // Constructor
        setTermoAritmetrico(_termoAritmetrico_);

    }

    @Override
    public Object clone()
    {
        return new ATermoExpAritmetrica(
            cloneNode(this._termoAritmetrico_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoExpAritmetrica(this);
    }

    public PTermoAritmetrico getTermoAritmetrico()
    {
        return this._termoAritmetrico_;
    }

    public void setTermoAritmetrico(PTermoAritmetrico node)
    {
        if(this._termoAritmetrico_ != null)
        {
            this._termoAritmetrico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoAritmetrico_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoAritmetrico_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoAritmetrico_ == child)
        {
            this._termoAritmetrico_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoAritmetrico_ == oldChild)
        {
            setTermoAritmetrico((PTermoAritmetrico) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
